[34m[1mwandb[0m: logging graph, to disable use `wandb.watch(log_graph=False)`
Epoch 0: |                                                                                                                                                                                                                                        | 167/? [01:06<00:00,  2.52it/s, v_num=6fti]
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x7e9ac72d8430>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
